config/routes.rb
Rails.application.routes.draw do

  get 'plays/show'

  devise_for :users, controllers: {
      omniauth_callbacks: "omniauth_callbacks"
  }
  root 'pages#index'
  get 'account', to: 'users#show', as: 'current_user'
  get 'play', to: 'plays#show', as: 'current_play'
  post 'plays/new', to: 'plays#create', as: 'new_play'
  delete 'play', to: 'plays#destroy', as: 'end_play'
  get 'room', to: 'rooms#show', as: 'current_room'
  post 'rooms/new', to: 'rooms#create', as: 'new_room'
  post 'rooms/search', to: 'rooms#search', as: 'search_room'
  delete 'rooms/exit', to: 'rooms#destroy', as: 'exit_room'
  resources :rulebooks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  serialize :stack
  serialize :operators

  has_many :social_profiles, dependent: :destroy
  belongs_to :room, required: false
  has_many :rulebooks

  validates :name, presence: true, length: { maximum: 50 }

  def social_profile(provider)
    social_profiles.select{ |sp| sp.provider == provider.to_s }.first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h1>CIRCLE</h1>
Hello, <%= current_user.name %>!
<%= link_to "Log out", destroy_user_session_path, method: :delete %><br/>
<% if current_user.room %>
    <%= link_to "Current Room '#{current_user.room.name}'", current_room_path %><br/>
<% end %>
<%= form_tag new_room_path, method: :post do %>
    <h2>Create Room</h2>
    <div class="field">
      <%= label :rooms, :name %><br />
      <%= text_field :rooms, :name %>
    </div>
    <div class="field">
      <%= label :rooms, :password %><br />
      <%= text_field :rooms, :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Create rooms" %>
    </div>

<% end %>

<%= form_tag search_room_path, method: :post do %>
    <h2>Search Room</h2>
    <div class="field">
      <%= label :rooms, :name %><br />
      <%= text_field :rooms, :name %>
    </div>
    <div class="field">
      <%= label :rooms, :password %><br />
      <%= text_field :rooms, :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Search Room" %>
    </div>
<% end %>

<h2>Rulebooks</h2>
<table>
  <tr>
    <th>Title</th>
    <th>updated_at</th>
    <th>created_at</th>
  </tr>
  <% current_user.rulebooks.each do |rulebook| %>
      <tr>
        <td><%= link_to rulebook.title, rulebook %></td>
        <td><%= rulebook.updated_at %></td>
        <td><%= rulebook.created_at %></td>
      </tr>
  <% end %>
</table>
<%= link_to "new rulebook", new_rulebook_path %>