config/routes.rb
Rails.application.routes.draw do

  get 'plays/show'

  devise_for :users, controllers: {
      omniauth_callbacks: "omniauth_callbacks"
  }
  root 'pages#index'
  get 'account', to: 'users#show', as: 'current_user'
  get 'play', to: 'plays#show', as: 'current_play'
  post 'plays/new', to: 'plays#create', as: 'new_play'
  delete 'play', to: 'plays#destroy', as: 'end_play'
  get 'room', to: 'rooms#show', as: 'current_room'
  post 'rooms/new', to: 'rooms#create', as: 'new_room'
  post 'rooms/search', to: 'rooms#search', as: 'search_room'
  delete 'rooms/exit', to: 'rooms#destroy', as: 'exit_room'
  resources :rulebooks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/index.html.erb
<h1>CIRCLE</h1>
<%= link_to "Log in", new_user_session_path %> <%= link_to "Sign up", new_user_registration_path %>

app/views/pages/room.html.erb
<div id="screen">
  <h1>Room <%= @current_room.name %></h1>
  <p>
    <label>name</label><br />
    <%= @current_room.name %><br />
    <label>password</label><br />
    <%= !@current_room.password.blank? ? @current_room.password : 'no password' %><br />
  </p>

  <p>
    <label>members</label>
  <ul id="member_list">
    <% @current_room.users.each do |member| %>
        <li><%= member.name %></li>
    <% end %>
  </ul>
  </p>
  <p>
    <label>rulebooks</label>
  <ul id="member_list">
    <% Rulebook.all.each do |rulebook| %>
        <li><a href="javascript: void(0)" onclick="App.user.push({'order': 'start', 'rulebook': <%= rulebook.id %>});"><%= rulebook.title %></a></li>
    <% end %>
  </ul>
  </p>
  <%= link_to 'exit room', exit_room_path, method: :delete %>
</div>