config/routes.rb
Rails.application.routes.draw do

  get 'plays/show'

  devise_for :users, controllers: {
      omniauth_callbacks: "omniauth_callbacks"
  }
  root 'pages#index'
  get 'account', to: 'users#show', as: 'current_user'
  get 'play', to: 'plays#show', as: 'current_play'
  post 'plays/new', to: 'plays#create', as: 'new_play'
  delete 'play', to: 'plays#destroy', as: 'end_play'
  get 'room', to: 'rooms#show', as: 'current_room'
  post 'rooms/new', to: 'rooms#create', as: 'new_room'
  post 'rooms/search', to: 'rooms#search', as: 'search_room'
  delete 'rooms/exit', to: 'rooms#destroy', as: 'exit_room'
  resources :rulebooks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rulebook.rb
class Rulebook < ApplicationRecord
  belongs_to :user
  serialize :task_code
  validates :title, presence: true
end

app/controllers/rulebooks_controller.rb
class RulebooksController < ApplicationController
  before_action :authenticate_user!
  def new
    @rulebook = current_user.rulebooks.new
  end
  def create
    @rulebook = current_user.rulebooks.new(params.require(:rulebook).permit(:title, :description, :code, :permission))
    begin
      task_code = Radius::RadiusMain.new.compile(@rulebook.code)
    rescue => e
      flash.now[:alert] = e
      render 'new' and return
    end
    @rulebook.task_code = task_code
    if @rulebook.save
      redirect_to @rulebook, notice: 'Created successfully'
    else
      flash.now[:alert] = 'title is empty'
      render 'new'
    end
  end
  def edit
    @rulebook = Rulebook.find(params[:id])
    redirect_to @rulebook unless @rulebook.user.id == current_user.id
  end
  def update
    @rulebook = Rulebook.find(params[:id])
    redirect_to @rulebook unless @rulebook.user.id == current_user.id

    begin
      task_code = Radius::RadiusMain.new.compile(params[:rulebook][:code])
    rescue => e
      flash.now[:alert] = e
      @rulebook.code = params[:rulebook][:code]
      render 'new' and return
    end
    @rulebook.update_attribute(:task_code, task_code)
    if @rulebook.update_attributes(params.require(:rulebook).permit(:title, :description, :code, :permission))
      redirect_to @rulebook, notice: 'Updated successfully'
    else
      flash.now[:alert] = 'title is empty'
      render 'new'
    end
  end
  def destroy
    @rulebook = Rulebook.find(params[:id])
    redirect_to @rulebook unless @rulebook.user.id == current_user.id
    @rulebook.destroy
    redirect_to root_path, notice: 'Destroyed successfully'
  end
  def show
    @rulebook = Rulebook.find(params[:id])
  end
end

app/helpers/rulebooks_helper.rb
module RulebooksHelper
end

app/views/rulebooks/_form.erb
<%= form_for @rulebook do |f| %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, autocomplete: "title" %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, autocomplete: "description" %>
    </div>
    <div class="field">
      <%= f.label :code %><br />
      <%= f.text_area :code, autocomplete: "code", class: 'form-control', rows: 20, id:'code' %>
    </div>
    <div id="result"></div>
    <div class="actions">
      <input type="button" value="Run" id="run">
      <input type="button" value="Stop" id="stop">
      <%= f.submit "Save" %>
    </div>
<% end %>
<script>
    <!--
    $("#run").click(function(){
        App.user.push({"order": "run_in_editor", "code": $("#code").val()})
    });
    $("#stop").click(function(){
        App.user.push({"order": "stop_in_editor"})
    });
    $(function(){
        $(window).on('beforeunload', function() {
            return '保存されていない可能性があります. このまま移動しますか？';
        });

        $("input[type=submit]").click(function() {
            $(window).off('beforeunload');
        });
    });
    //-->
</script>

app/views/rulebooks/edit.html.erb
<h2>Edit Rulebook</h2>

<%= render 'form' %>
<%= link_to "back", current_user_path %>

app/views/rulebooks/new.html.erb
<h2>New Rulebook</h2>

<%= render 'form' %>
<%= link_to "back", current_user_path %>

app/views/rulebooks/show.html.erb
<h1><%= @rulebook.title %></h1>
<% if user_signed_in? && current_user.id == @rulebook.user.id %>
  <%= link_to "edit rulebook", edit_rulebook_path %>
  <%= link_to "delete rulebook", rulebook_path, method: :delete %>
<% end %>
<h2>Description</h2>
<p><%= @rulebook.description %></p>
<h2>Code</h2>
<p><%= simple_format(@rulebook.code.gsub("\s", "&nbsp;")) %></p>
<h2>Task Code</h2>
<table class="table table-striped" style="width:50%">
  <tr>
    <th></th>
    <th>Ope</th>
    <th>Ln</th>
    <th>Val</th>
    <th>Stk</th>
  </tr>
  <% if @rulebook.task_code %>
      <% @rulebook.task_code.each_with_index do |task, index| %>
          <tr>
            <th><%= index %></th>
            <td><%= task[0] %></td>
            <td><%= task[1] %></td>
            <td><%= task[2] %></td>
            <td><%= task[3] %></td>
          </tr>
      <% end %>
  <% end %>
</table>

<%= link_to "back", current_room_path %>